[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16.13.2" }

[dev]
  command = "npm start"
  publish = "dist"

[[edge_functions]]
  function = "time"
  path = "/"
